AWSTemplateFormatVersion: 2010-09-09

Description: Builds and runs the kinesis-analytics-taxi-consumer Flink application in a fully managed environment using Amazon Kinesis Data Analytics for Java Applications (amazon-kinesis-analytics-taxi-consumer)

Parameters:
  TemplateBucket:
    Description: Bucket containing the CloudFormation templates
    Type: String

  SshKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EC2 instance for replaying events
    ConstraintDescription: MuSt be the name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  ClientIpAddressRange:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Description: IP address range that is able to access the EC2 instance and that gets full read and write access to the Elasticsearch Cluster and the Kibana dashboard
    MaxLength: 18
    MinLength: 9
    Type: String


Outputs:
  KinesisReplayInstance:
    Description: SSH connection to the instance that ingests trip events into the Kinesis stream
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.KinesisReplayInstance

  ProducerCommand:
    Description: Command to populate Kinesis stream with taxi trip events
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.ProducerCommand

  CloudWatchDashboardURL:
    Description: URL to access metrics in a CloudWatch dasboard
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.CloudWatchDashboardURL

  OutputDataBucket:
    Description: Output Data Bucket
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.OutputDataBucket

  InputDataAccumulatorBucket:
    Description: Input Data Accumulator Bucket
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.InputDataAccumulatorBucket



Resources:
  KinesisReplayBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/kinesis-replay-build-pipeline.yml
      Parameters:
        ExternalArtifactBucket: !Ref ArtifactBucket
        Release: release-0.1.0

  FlinkKinesisConnectorBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/flink-kinesis-connector-build-pipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket

  TaxiConsumerBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/kinesis-analytics-taxi-consumer-build-pipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket

  TaxiConsumerInfrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/kinesis-analytics-taxi-consumer-infrastructure.yml
      Parameters:
        KinesisReplayCopyCommand: !GetAtt KinesisReplayBuildStack.Outputs.KinesisReplayCopyCommand
        FlinkApplicationS3BucketArn: !GetAtt ArtifactBucket.Arn
        FlinkApplicationS3Path: !GetAtt TaxiConsumerBuildStack.Outputs.FlinkApplicationS3Path
        SshKeyName: !Ref SshKeyName
        ClientIpAddressRange: !Ref ClientIpAddressRange

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
