AWSTemplateFormatVersion: 2010-09-09

Description: Builds and runs the Kinesis Producer application.

Parameters:
  TemplateBucket:
    Description: Bucket containing the CloudFormation templates
    Type: String

  SshKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EC2 instance
    ConstraintDescription: MuSt be the name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  ClientIpAddressRange:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Description: IP address range that is able to access the EC2 instance
    MaxLength: 18
    MinLength: 9
    Type: String

  InputKinesisStreamName:
    Type: String
    

Outputs:
  KinesisProducerSshCommand:
    Description: SSH connection to the instance that ingests trip events into the Kinesis stream
    Value: !GetAtt ProducerAwsInfrastructure.Outputs.KinesisProducerSshCommand

  KinesisProducerRunCommand:
    Description: Command to populate Kinesis stream with taxi trip events
    Value: !GetAtt ProducerAwsInfrastructure.Outputs.KinesisProducerRunCommand


Resources:
  KinesisProducerBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/kinesis-producer-build.yml
      Parameters:
        ExternalArtifactBucket: !Ref ArtifactBucket
        
  
  ProducerAwsInfrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/producer-aws-infrastructure.yml
      Parameters:
        KinesisProducerCopyCommand: !GetAtt KinesisProducerBuildStack.Outputs.KinesisProducerCopyCommand
        ArtifactBucketArn: !GetAtt ArtifactBucket.Arn
        InputKinesisStreamName: !Sub ${InputKinesisStreamName}
        SshKeyName: !Ref SshKeyName
        ClientIpAddressRange: !Ref ClientIpAddressRange

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
