AWSTemplateFormatVersion: 2010-09-09

Description: Builds and runs the kinesis-analytics-taxi-consumer Flink application in a fully managed environment using Amazon Kinesis Data Analytics for Java Applications (amazon-kinesis-analytics-taxi-consumer)

Parameters:
  TemplateBucket:
    Description: Bucket containing the CloudFormation templates
    Type: String

  SshKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EC2 instance for replaying events
    ConstraintDescription: MuSt be the name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  ClientIpAddressRange:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Description: IP address range that is able to access the EC2 instance and that gets full read and write access to the Elasticsearch Cluster and the Kibana dashboard
    MaxLength: 18
    MinLength: 9
    Type: String


Outputs:
  
  CloudWatchDashboardURL:
    Description: URL to access metrics in a CloudWatch dasboard
    Value: !GetAtt KinesisAnalyticsAwsInfrastructure.Outputs.CloudWatchDashboardURL

  KinesisAnalyticsApplicationURL:
    Value: !GetAtt KinesisAnalyticsAwsInfrastructure.Outputs.KinesisAnalyticsApplicationURL

  InputKinesisStreamMonitoringURL:
    Value: !GetAtt KinesisAnalyticsAwsInfrastructure.Outputs.InputKinesisStreamMonitoringURL

  OutputFirehoseStreamMonitoringURL:
    Value: !GetAtt KinesisAnalyticsAwsInfrastructure.Outputs.OutputFirehoseStreamMonitoringURL

  OutputDataBucketURL:
    Description: Output Data Bucket
    Value: !GetAtt KinesisAnalyticsAwsInfrastructure.Outputs.OutputDataBucketURL

  InputDataAccumulatorBucketURL:
    Description: Input Data Accumulator Bucket
    Value: !GetAtt KinesisAnalyticsAwsInfrastructure.Outputs.InputDataAccumulatorBucketURL


Resources:
  
  FlinkKinesisConnectorBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/flink-kinesis-connector-build.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket

  FlinkConsumerBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/flink-consumer-build.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket

  KinesisAnalyticsAwsInfrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/kinesis-analytics-aws-infrastructure.yml
      Parameters:
        FlinkConsumerS3BucketArn: !GetAtt ArtifactBucket.Arn
        FlinkConsumerS3Path: !GetAtt FlinkConsumerBuildStack.Outputs.FlinkConsumerS3Path
        SshKeyName: !Ref SshKeyName
        ClientIpAddressRange: !Ref ClientIpAddressRange

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
